### ISSUE TITLE
new commit run error

### ISSUE THREAD

**Issue by zdx3578** [nottombrown/rl-teacher#33]
Traceback (most recent call last):
Traceback (most recent call last):
Traceback (most recent call last):
  File "/home/sdc/anaconda3/lib/python3.6/multiprocessing/process.py", line 249, in _bootstrap
    self.run()
  File "/home/sdc/anaconda3/lib/python3.6/multiprocessing/process.py", line 249, in _bootstrap
    self.run()
  File "/home/sdc/anaconda3/lib/python3.6/multiprocessing/process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
  File "/home/sdc/anaconda3/lib/python3.6/multiprocessing/process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
  File "/home/sdc/anaconda3/lib/python3.6/multiprocessing/pool.py", line 119, in worker
    result = (True, func(*args, **kwds))
  File "/home/sdc/anaconda3/lib/python3.6/multiprocessing/pool.py", line 119, in worker
    result = (True, func(*args, **kwds))
  File "/home/sdc/github/rl-teacher/rl_teacher/comparison_collectors.py", line 55, in _write_and_upload_video
    upload_to_gcs(local_path, gcs_path)
  File "/home/sdc/anaconda3/lib/python3.6/multiprocessing/process.py", line 249, in _bootstrap
    self.run()
  File "/home/sdc/github/rl-teacher/rl_teacher/comparison_collectors.py", line 55, in _write_and_upload_video
    upload_to_gcs(local_path, gcs_path)
  File "/home/sdc/github/rl-teacher/rl_teacher/video.py", line 138, in upload_to_gcs
    subprocess.check_call(['gsutil', 'cp', local_path, gcs_path])
  File "/home/sdc/anaconda3/lib/python3.6/multiprocessing/process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
  File "/home/sdc/github/rl-teacher/rl_teacher/video.py", line 138, in upload_to_gcs
    subprocess.check_call(['gsutil', 'cp', local_path, gcs_path])
  File "/home/sdc/anaconda3/lib/python3.6/subprocess.py", line 286, in check_call
    retcode = call(*popenargs, **kwargs)
  File "/home/sdc/anaconda3/lib/python3.6/multiprocessing/pool.py", line 119, in worker
    result = (True, func(*args, **kwds))
  File "/home/sdc/anaconda3/lib/python3.6/multiprocessing/process.py", line 249, in _bootstrap
    self.run()
  File "/home/sdc/github/rl-teacher/rl_teacher/comparison_collectors.py", line 55, in _write_and_upload_video
    upload_to_gcs(local_path, gcs_path)
  File "/home/sdc/anaconda3/lib/python3.6/subprocess.py", line 286, in check_call
    retcode = call(*popenargs, **kwargs)
  File "/home/sdc/anaconda3/lib/python3.6/subprocess.py", line 269, in call
    return p.wait(timeout=timeout)
  File "/home/sdc/anaconda3/lib/python3.6/multiprocessing/process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
  File "/home/sdc/github/rl-teacher/rl_teacher/video.py", line 138, in upload_to_gcs
    subprocess.check_call(['gsutil', 'cp', local_path, gcs_path])
  File "/home/sdc/anaconda3/lib/python3.6/subprocess.py", line 269, in call
    return p.wait(timeout=timeout)
  File "/home/sdc/anaconda3/lib/python3.6/subprocess.py", line 1439, in wait
    (pid, sts) = self._try_wait(0)
  File "/home/sdc/anaconda3/lib/python3.6/multiprocessing/pool.py", line 119, in worker
    result = (True, func(*args, **kwds))
  File "/home/sdc/anaconda3/lib/python3.6/subprocess.py", line 286, in check_call
    retcode = call(*popenargs, **kwargs)
  File "/home/sdc/anaconda3/lib/python3.6/subprocess.py", line 1439, in wait
    (pid, sts) = self._try_wait(0)
  File "/home/sdc/anaconda3/lib/python3.6/subprocess.py", line 1386, in _try_wait
    (pid, sts) = os.waitpid(self.pid, wait_flags)
  File "/home/sdc/github/rl-teacher/rl_teacher/comparison_collectors.py", line 55, in _write_and_upload_video
    upload_to_gcs(local_path, gcs_path)
  File "/home/sdc/anaconda3/lib/python3.6/subprocess.py", line 269, in call
    return p.wait(timeout=timeout)
  File "/home/sdc/anaconda3/lib/python3.6/subprocess.py", line 1386, in _try_wait
    (pid, sts) = os.waitpid(self.pid, wait_flags)
  File "/home/sdc/github/rl-teacher/rl_teacher/video.py", line 138, in upload_to_gcs
    subprocess.check_call(['gsutil', 'cp', local_path, gcs_path])
  File "/home/sdc/anaconda3/lib/python3.6/subprocess.py", line 1439, in wait
    (pid, sts) = self._try_wait(0)
  File "/home/sdc/anaconda3/lib/python3.6/subprocess.py", line 286, in check_call
    retcode = call(*popenargs, **kwargs)
KeyboardInterrupt
  File "/home/sdc/anaconda3/lib/python3.6/subprocess.py", line 1386, in _try_wait
    (pid, sts) = os.waitpid(self.pid, wait_flags)
  File "/home/sdc/anaconda3/lib/python3.6/subprocess.py", line 269, in call
    return p.wait(timeout=timeout)
KeyboardInterrupt
  File "/home/sdc/anaconda3/lib/python3.6/subprocess.py", line 1439, in wait
    (pid, sts) = self._try_wait(0)
  File "/home/sdc/anaconda3/lib/python3.6/subprocess.py", line 1386, in _try_wait
    (pid, sts) = os.waitpid(self.pid, wait_flags)

**Comment by zdx3578** [comment]
(2,) (11,)
---------
Traceback (most recent call last):
  File "rl_teacher/teach.py", line 330, in <module>
    main()
  File "rl_teacher/teach.py", line 275, in main
    label_schedule=label_schedule,
  File "rl_teacher/teach.py", line 63, in __init__
    self.graph = self._build_model()
  File "rl_teacher/teach.py", line 114, in _build_model
    self.q_value = self._predict_rewards(self.segment_obs_placeholder, self.segment_act_placeholder, mlp)
  File "rl_teacher/teach.py", line 81, in _predict_rewards
    rewards = network.run(obs, acts)
TypeError: run() takes 2 positional arguments but 3 were given

**Comment by nottombrown** [comment]
Closing because I can't replicate.
